### ISSUE TITLE
logs: use iso8601(-like) format

### ISSUE THREAD

**Issue by fromanirh** [k8stopologyawareschedwg/resource-topology-exporter#119]
the RTE logs should include the date, not just the time, in their timestamp

**Comment by Tal-or** [comment]
RTE logs already contain the date.
Header explanation can be found here: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md#logging-formats

**Comment by fromanirh** [comment]
thanks for the findings! good enough to close.
