### ISSUE TITLE
Set OwnerReference for NRT objects

### ISSUE THREAD

**Issue by ffromani** [k8stopologyawareschedwg/resource-topology-exporter#203]
Should we follow the example of the [DRA example driver](https://github.com/kubernetes-sigs/dra-example-driver) and set OwnerReferences backlinking to nodes to the NRT objects?

**Comment by jlojosnegros** [comment]
I gonna take this, if that is ok.

Is the target to add the Node as Owner of the NRT to trigger deletion if a node is deleted from the cluster or the discussion about if doing so its ok?

**Comment by ffromani** [comment]
go for it! the main benefit of this change is to avoid leftovers in the cluster: if a node object gets deleted, the corresponding NRT should be deleted as well (no stale objects).
Truth to be told, I expect this flow to trigger extremely rarely, but still why not?

**Comment by jlojosnegros** [comment]
/close 
as #212  is merged
