### ISSUE TITLE
update golang toolchain to 1.20

### ISSUE THREAD

**Issue by ffromani** [k8stopologyawareschedwg/resource-topology-exporter#209]
move CI and requirements to latest 1.20

**Comment by jlojosnegros** [comment]
I have started this on #213 but I am not sure if the CI part is properly handled ( I think it is not ) so could you please elaborate on that? 

Thanks in advance.

**Comment by ffromani** [comment]
"CI and requirements" meant go.mod and all the reference to golang version on the github actions flows and on scripts

**Comment by jlojosnegros** [comment]
> "CI and requirements" meant go.mod and all the reference to golang version on the github actions flows and on scripts

Ok thanks. Then I think I have that covered.
