### ISSUE TITLE
The unit for hugepages is a page, not equivalent bytes of memory

### ISSUE THREAD

**Issue by jaypipes** [k8stopologyawareschedwg/resource-topology-exporter#243]
When dealing with hugepage resources, the unit of the resource is an entire page (typically either 2Mi or 1Gi sizes). The unit of the resource is *not* the amount of memory in bytes. Users of hugepage resources request X number of pages, not X amount of memory.

In our use of resource-topology-exporter and NUMA-aware scheduling plugins, we are seeing inaccurate reporting of hugepage resources. For instance, our compute worker nodes have 2 NUMA cells and each NUMA cell has 256Gi of RAM. Of that 256Gi RAM, we create 224 1Gi hugepages that we are able to allocate to workloads on the node.

Unfortunately, when we look at the amounts reported for each NUMA cell, we get this:

```
root@b37dev07c2mg01 [ ~ ]# kubectl get noderesourcetopologies/b37dev07c1co02 -ojsonpath='{.zones}' | jq
[
  {
    "costs": [
      {
        "name": "node-0",
        "value": 10
      },
      {
        "name": "node-1",
        "value": 20
      }
    ],
    "name": "node-0",
    "resources": [
      {
        "allocatable": "58",
        "available": "45",
        "capacity": "58",
        "name": "mellanox.com/mlnx_sriov_vfio"
      },
      {
        "allocatable": "52",
        "available": "44",
        "capacity": "56",
        "name": "cpu"
      },
      {
        "allocatable": "240518168576",
        "available": "201863462912",
        "capacity": "240518168576",
        "name": "hugepages-1Gi"
      },
      {
        "allocatable": "28606324736",
        "available": "25636757503",
        "capacity": "269661364224",
        "name": "memory"
      },
      {
        "allocatable": "6",
        "available": "6",
        "capacity": "6",
        "name": "mellanox.com/mlnx_sriov"
      }
    ],
    "type": "Node"
  },
  {
    "costs": [
      {
        "name": "node-0",
        "value": 20
      },
      {
        "name": "node-1",
        "value": 10
      }
    ],
    "name": "node-1",
    "resources": [
      {
        "allocatable": "6",
        "available": "6",
        "capacity": "6",
        "name": "mellanox.com/mlnx_sriov"
      },
      {
        "allocatable": "58",
        "available": "58",
        "capacity": "58",
        "name": "mellanox.com/mlnx_sriov_vfio"
      },
      {
        "allocatable": "52",
        "available": "52",
        "capacity": "56",
        "name": "cpu"
      },
      {
        "allocatable": "240518168576",
        "available": "240518168576",
        "capacity": "240518168576",
        "name": "hugepages-1Gi"
      },
      {
        "allocatable": "29461528576",
        "available": "29461528576",
        "capacity": "270516568064",
        "name": "memory"
      }
    ],
    "type": "Node"
  }
]
```

I believe this may be due to an error here:

https://github.com/k8stopologyawareschedwg/resource-topology-exporter/blob/d641fcbb7548070041a1afdda4b87230d8661f72/pkg/sysinfo/sysinfo.go#L63

However, after looking at [the upstream documentation about hugepage resources](https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/), it seems that upstream Kubernetes has just got it completely wrong. They are treating hugepages as units of bytes instead of properly as pages. :(

**Comment by ffromani** [comment]
Hi @jaypipes thanks for the report and sorry for the delayed answer. 
Yes, the core thing here is the accounting needs to be done the same way core k8s do, so we need to use bytes, not pages, even though doing like this force us to this awkward conversion.

I'm contemplating if we can expose both values actually, adding an extra resource which represent hugepage count.
I'm not sure if this will turn out more confusing though.

**Comment by ffromani** [comment]
for reasons stated in https://github.com/k8stopologyawareschedwg/resource-topology-exporter/issues/243#issuecomment-1880453467 nothing we can fix here atm
