### ISSUE TITLE
Get rid of vendoring

### ISSUE THREAD

**Issue by jaypipes** [k8stopologyawareschedwg/resource-topology-exporter#293]
We (Microsoft Network Cloud) have a mirror of this repo internally for software supply chain purposes and the `vendor/` directory makes the mirror maintenance unnecessarily painful. Modern Go and modules are a cleaner, more maintainable way to manage dependencies.

**Comment by ffromani** [comment]
I do have nothing against removing `vendor/` in principle. Let's see how we want to do it.

**Comment by ffromani** [comment]
closed thanks to #294
