### ISSUE TITLE
notification events from CRI runtime

### ISSUE THREAD

**Issue by fromanirh** [k8stopologyawareschedwg/resource-topology-exporter#39]
The major container runtimes, containerd and cri-o, both offer extensive hooking mechanism we can leverage to get container lifecycle events while the podresources API catches up. It could work like this:
1. the RTE opens a notification socket on a well known location
2. RTE offer a client program to be called from the CRI runtime hooks
3. When a noteworthy container lifeycle event (create and remove; what else?) happens, the hook calls the client to notify RTE
4. Depending on further design decisions, RTE either trusts the client program with the data it received from the notification socket, or performs a full `GetAllocatable`/`List` poll to update its status.

**Comment by swatisehgal** [comment]
This is a good idea and definitely worth exploring! Currently, I only see `PreStart` and `PostStop` hooks [here](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks) which should take care of the container lifecycle event you mentioned above (create and remove). In addition to this, I can think of `update` lifecycle event where resources are updated but that could be phase 2 of this work.

**Comment by AlexeyPerevalov** [comment]
@swatisehgal, @fromanirh my college interested in this, but for solving issues with PLEG.
He has a draft at https://github.com/ikeeip/containerd/tree/cri_subscribe_events

**Comment by fromanirh** [comment]
@AlexeyPerevalov very nice! thanks for letting us know. I'll surely have a look ASAP.

**Comment by fromanirh** [comment]
implemented in https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/54 (merged)
